#!/usr/bin/env python3
"""Per-map (and pooled) summary of the FSE multi-map campaign.

Reads fse_summary.json produced by aggregate_fse_search.py and writes:
  per_map_summary.json / .md   -- per-map means per policy
  per_map_table.tex            -- LaTeX table fragment for the paper

Usage:
  research/.venv/bin/python research/scripts/per_map_summary.py \
    --summary research/logs/fse_search/fse_summary.json \
    --out-dir research/logs/fse_search
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

POLICIES = ("semantic", "random", "lsa", "kmnc")
DIMS = ("V", "A", "E", "H")


def mean(xs):
    return sum(xs) / len(xs) if xs else float("nan")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, required=True)
    args = ap.parse_args()

    data = json.loads(args.summary.read_text())
    arms = data["arms"]

    # completeness: search arms target 50, controls 8
    def complete(a):
        return a["policy"] == "control" or a["n_valid_rows"] >= 50

    by_map = defaultdict(lambda: defaultdict(list))   # map -> policy -> [arm]
    pooled = defaultdict(list)                        # policy -> [arm]
    n_routes = defaultdict(set)
    for a in arms:
        if a["policy"] == "control" or not complete(a):
            continue
        m = a["route"].split("_")[0]
        by_map[m][a["policy"]].append(a)
        pooled[a["policy"]].append(a)
        n_routes[m].add(a["route"])

    def agg(arms_list):
        out = {}
        for d in DIMS:
            out[f"cov_{d.lower()}"] = mean([a["final_cov"][d] for a in arms_list])
            out[f"auc_{d.lower()}"] = mean([a["auc"][f"auc_{d.lower()}"] for a in arms_list])
        out["n_closed"] = mean([a["discovery"]["n_closed"] for a in arms_list])
        out["n"] = len(arms_list)
        return out

    result = {"by_map": {}, "pooled": {}, "routes_by_map": {m: sorted(rs) for m, rs in n_routes.items()}}
    for m in sorted(by_map):
        result["by_map"][m] = {p: agg(by_map[m][p]) for p in POLICIES if by_map[m][p]}
    result["pooled"] = {p: agg(pooled[p]) for p in POLICIES if pooled[p]}
    result["complete_arms"] = sum(len(v) for v in by_map.values())

    out_json = args.out_dir / "per_map_summary.json"
    out_json.write_text(json.dumps(result, indent=2))

    # Markdown
    lines = ["# Per-map semantic coverage (endpoint, mean over routes)\n"]
    lines.append("| Map | Routes | Semantic E/H | Random E/H | LSA E/H | KMNC E/H |")
    lines.append("|---|---|---|---|---|---|")
    for m in sorted(result["by_map"]):
        cell = {}
        for p in POLICIES:
            a = result["by_map"][m].get(p)
            cell[p] = f"{a['cov_e']:.3f}/{a['cov_h']:.3f}" if a else "--"
        lines.append(
            f"| {m} | {len(result['routes_by_map'][m])} | {cell['semantic']} | "
            f"{cell['random']} | {cell['lsa']} | {cell['kmnc']} |"
        )
    lines.append("")
    lines.append("## Pooled over all maps (endpoint / AUC)\n")
    lines.append("| Policy | Cov_V | Cov_A | Cov_E | Cov_H | AUC_E | AUC_H | closed |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for p in POLICIES:
        a = result["pooled"].get(p)
        if not a:
            continue
        lines.append(
            f"| {p} | {a['cov_v']:.3f} | {a['cov_a']:.3f} | {a['cov_e']:.3f} | {a['cov_h']:.3f} | "
            f"{a['auc_e']:.3f} | {a['auc_h']:.3f} | {a['n_closed']:.1f} |"
        )
    (args.out_dir / "per_map_summary.md").write_text("\n".join(lines) + "\n")

    # LaTeX fragment
    tex = []
    tex.append("% Auto-generated by per_map_summary.py -- per-map endpoint Cov_E / Cov_H")
    tex.append("\\begin{tabular}{@{}lrrrr@{}}")
    tex.append("\\toprule")
    tex.append("Map (routes) & Semantic & Random & LSA & KMNC \\\\")
    tex.append("\\midrule")
    for m in sorted(result["by_map"]):
        cells = []
        best = {}
        for p in POLICIES:
            a = result["by_map"][m].get(p)
            val = a["cov_h"] if a else float("-inf")
            best[p] = val
        top = max(best.values()) if best else 0.0
        for p in POLICIES:
            a = result["by_map"][m].get(p)
            if not a:
                cells.append("--")
                continue
            e, h = a["cov_e"], a["cov_h"]
            s = f"${e:.3f}$ / ${h:.3f}$"
            if abs(h - top) < 1e-9:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        label = m.replace("town", "Town").replace("hd", "HD")
        tex.append(f"{label} ({len(result['routes_by_map'][m])}) & " + " & ".join(cells) + " \\\\")
    tex.append("\\bottomrule")
    tex.append("\\end{tabular}")
    (args.out_dir / "per_map_table.tex").write_text("\n".join(tex) + "\n")

    print(f"complete arms: {result['complete_arms']}")
    print(f"maps: {sorted(result['by_map'])}")
    for p in POLICIES:
        a = result["pooled"].get(p)
        if a:
            print(f"pooled {p:9s} E {a['cov_e']:.3f} H {a['cov_h']:.3f} AUC_E {a['auc_e']:.3f} AUC_H {a['auc_h']:.3f} closed {a['n_closed']:.1f}")
    print(f"wrote {out_json}, per_map_summary.md, per_map_table.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
