[project]
name = "mres-research-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.12"
dependencies = [
    "carla==0.9.16",
    "joblib>=1.5.3",
    "matplotlib>=3.7,<4",
    "networkx>=3.4.2",
    "numpy<2.0.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.15,<2",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = ["pytest>=8,<9"]

[project.optional-dependencies]
perception = [
    "pillow==9.2.0",
    "scallopy",
    "sentencepiece>=0.2.0",
    "transformers==4.46.2",
]
runpod = [
    "runpod>=1.7.0",
]
transfuser = [
    "dictor==0.1.12",
    "easydict==1.9",
    "ephem==4.2",
    "imgaug==0.4.0",
    "opencv-python==4.6.0.66 ; sys_platform == 'win32'",
    "pillow==9.2.0",
    "psutil==7.1.0",
    "py-trees==0.8.3",
    "pygame==2.6.1",
    "scikit-image==0.20.0",
    "setuptools<81",
    "tabulate==0.9.0",
    "timm==0.6.7",
    "torch==2.11.0 ; sys_platform == 'win32'",
    "torchaudio>=2.11.0 ; sys_platform == 'win32'",
    "torchvision>=0.26.0 ; sys_platform == 'win32'",
    "tqdm==4.64.1",
    "ujson==5.4.0",
    "xmlschema==1.0.18",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch", marker = "sys_platform == 'win32'" }
torchaudio = { index = "pytorch", marker = "sys_platform == 'win32'" }
torchvision = { index = "pytorch", marker = "sys_platform == 'win32'" }
scallopy = { git = "https://github.com/scallop-lang/scallop.git", subdirectory = "etc/scallopy" }
